### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by zf1976**
fix refresh_token grant_type to get the name: Principal.class.getName(), which causes an error in NPE.

### CODE REVIEW

**Comment by zf1976** [comment]
in `OAuth2RefreshTokenAuthenticationProvider` -> `public Authentication authenticate(Authentication authentication) throws AuthenticationException`

- code
```
		JwtEncodingContext context = JwtEncodingContext.with(headersBuilder, claimsBuilder)
				.registeredClient(registeredClient)
				.principal(authorization.getAttribute(Principal.class.getName()))  // here
				.authorization(authorization)
				.authorizedScopes(authorizedScopes)
				.tokenType(OAuth2TokenType.ACCESS_TOKEN)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.authorizationGrant(refreshTokenAuthentication)
				.build();
		// @formatter:on
```

**Review by Basit-Mahmood — APPROVED** [review]

**Comment by Basit-Mahmood** [comment]
Merging changes made by zf1976 for OAuth2ResourceOwnerPasswordAuthenticationProvider to resolve NPE in OAuth2RefreshTokenAuthenticationProvider. When try to get refresh token for password grant type.

**Review by Basit-Mahmood — COMMENTED** [review]
Thanks for pointing this out. Thank you so much.

**Comment by zf1976** [comment]
Sure, no problem.

> much

Sure, no problem.

**Pull request merged**
